// Generated by CoffeeScript 1.6.2
module.exports = function(app) {
  var die_on_error, types;

  die_on_error = require('./util').die_on_error;
  types = require('./rest').types;
  app.get('/', function(req, res) {
    return res.render('login');
  });
  return app.get('/library/:user_id', function(req, res) {
    var user_id;

    user_id = req.params.user_id;
    return types.user.get(user_id, die_on_error(res, function(user) {
      var _base, _base1, _ref, _ref1, _ref2;

      if ((_ref = user.library) == null) {
        user.library = {};
      }
      if ((_ref1 = (_base = user.library).images) == null) {
        _base.images = [];
      }
      if ((_ref2 = (_base1 = user.library).code) == null) {
        _base1.code = [];
      }
      return res.render('library', {
        user: user
      });
    }));
  });
};
