// Generated by CoffeeScript 1.3.3
var get, get_json, redis, redis_db, redis_password, redis_url, set, set_json, url, _ref, _ref1;

url = require('url');

redis_url = url.parse((_ref = process.env.REDISTOGO_URL) != null ? _ref : 'redis://localhost:6379');

redis = (require('redis')).createClient(redis_url.port, redis_url.hostname);

if (redis_url.auth) {
  _ref1 = redis_url.auth.split(':'), redis_db = _ref1[0], redis_password = _ref1[1];
  redis.auth(redis_password);
}

set = function(key, value, callback) {
  return redis.set(key, value, callback);
};

get = function(key, callback) {
  return redis.get(key, function(err, res) {
    if (err != null) {
      return callback(err);
    } else {
      return callback(null, res);
    }
  });
};

set_json = function(key, value, callback) {
  return set(key, JSON.stringify(value), callback);
};

get_json = function(key, callback) {
  return get(key, function(err, res) {
    var json_res, _ref2;
    if (err != null) {
      return callback(err);
    } else {
      _ref2 = (function() {
        try {
          return [null, JSON.parse(res)];
        } catch (e) {
          return ["Invalid JSON at key " + key, null];
        }
      })(), err = _ref2[0], json_res = _ref2[1];
      return callback(err, json_res);
    }
  });
};

module.exports = {
  set: set,
  get: get,
  set_json: set_json,
  get_json: get_json,
  redis: redis
};
