// Generated by CoffeeScript 1.3.3
var arg_map, die_on_error, fail_on_error, _,
  __slice = [].slice;

_ = require('underscore');

fail_on_error = function(error, success) {
  return function() {
    var err, rest;
    err = arguments[0], rest = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (typeof err === "function" ? err(error(err)) : void 0) {

    } else {
      return success.apply(null, rest);
    }
  };
};

die_on_error = function(res, fn) {
  return fail_on_error((function(err) {
    return res.send(500, err);
  }), fn);
};

arg_map = function() {
  var arg_object, args, fn, _i;
  fn = arguments[0], args = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), arg_object = arguments[_i++];
  return fn.apply(null, _(args).map(function(arg) {
    return arg_object[arg];
  }));
};

module.exports = {
  fail_on_error: fail_on_error,
  die_on_error: die_on_error,
  arg_map: arg_map
};
